services:
  viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "educative-viewer"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /home/user/Downloads/personal/educative/courses:/course_data
    environment:
      - FLASK_APP=educative-viewer
      - course_dir=/course_data
      - authtoken=keystring
      - downloadtoken=keystring
    command: sh -c "mkdir -p /root/EducativeViewer && gunicorn --workers=2 -b 0.0.0.0:5000 'educative-viewer:create_app()'"
